// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2A9QhPHodqS2FWBLpTYLUdNp-9xXSUc',
    appId: '1:368671038321:web:3f42f3b21a5c9f04d174d0',
    messagingSenderId: '368671038321',
    projectId: 'twitter-dev-1bb67',
    authDomain: 'twitter-dev-1bb67.firebaseapp.com',
    storageBucket: 'twitter-dev-1bb67.appspot.com',
    measurementId: 'G-WL94DBFMM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBp1H5rf2yDOKedGoqiPYexbyqwc-4vVA',
    appId: '1:368671038321:android:aaec9cd4963f0718d174d0',
    messagingSenderId: '368671038321',
    projectId: 'twitter-dev-1bb67',
    storageBucket: 'twitter-dev-1bb67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrVWtTSvhF0ZD8b88Gu8KnABVLbtRSTg',
    appId: '1:368671038321:ios:057eeb4b317b4a94d174d0',
    messagingSenderId: '368671038321',
    projectId: 'twitter-dev-1bb67',
    storageBucket: 'twitter-dev-1bb67.appspot.com',
    androidClientId: '368671038321-df341qo4h9a5o2e8oa1h1sr85du2v57e.apps.googleusercontent.com',
    iosClientId: '368671038321-hjeoqcavka82pe32srm6qvbu7j9sh191.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjrVWtTSvhF0ZD8b88Gu8KnABVLbtRSTg',
    appId: '1:368671038321:ios:057eeb4b317b4a94d174d0',
    messagingSenderId: '368671038321',
    projectId: 'twitter-dev-1bb67',
    storageBucket: 'twitter-dev-1bb67.appspot.com',
    androidClientId: '368671038321-df341qo4h9a5o2e8oa1h1sr85du2v57e.apps.googleusercontent.com',
    iosClientId: '368671038321-hjeoqcavka82pe32srm6qvbu7j9sh191.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterapp',
  );
}
